### PR TITLE
Fix deprecation warnings on julia v0.6

### PR DESCRIPTION
**Pull request by visr**
Note that this no longer extends `./` from Base, so technically breaking.

### CODE REVIEW

**Comment by visr** [comment]
Pending JuliaGeo/GeoInterface.jl#10, after that is merged and tagged we should REQUIRE the new GeoInterface version.

**Comment by yeesian** [comment]
Since we're onto breaking changes now, I'm not sure why we even decide on supporting the operations `+` and `-` for `Point`. What are your thoughts on removing them as well?

**Comment by visr** [comment]
Agreed to remove. And what about the Compose code?

**Comment by yeesian** [comment]
> And what about the Compose code?

It seems unnecessarily breaking for now. I'll be in favour of removing it once we have something else we can point people to.

**Comment by yeesian** [comment]
@jiahao do you still rely on the compose code? based on https://github.com/jiahao/ijulia-notebooks/blob/master/2014-06-30-world-of-julia.ipynb

**Comment by visr** [comment]
I removed the `+` and `/` on `Point`.

`compose.jl` is left as is for now. I just added a note that it won't ever be included in julia v0.6.

I added one more breaking change, let me know if you disagree, by removing `export Handle`.

**Comment by yeesian** [comment]
> I added one more breaking change, let me know if you disagree, by removing `export Handle`.

Yeah I think that's a good call too. Thanks!

**Pull request merged**
