### PR TITLE
move CI to github workflows

### PR DESCRIPTION
**Pull request by rafaqz**

### CODE REVIEW

**Comment by rafaqz** [comment]
Looks like something is returning `String` instead of `Symbol` now.

**Comment by visr** [comment]
Ah, that's just a DataFrames change, so we only need to update the tests there.

**Comment by rafaqz** [comment]
This seems good to go if you want to check the changes I've made. 

In addition to the DataFrames errors there were some uses of `joinpath` on both urls and file paths that broke on windows builds.

**Comment by evetion** [comment]
Looks good to me, thanks!

**Pull request merged**
