### PR TITLE
Implement Geointerface

### PR DESCRIPTION
**Pull request by yeesian**

### CODE REVIEW

**Comment by visr** [comment]
I quite like this :+1:

Can you comment a bit on how you see the GeoInterface being used? How I see it now, we can make the types in the packages subtypes of the right GeoInterface abstract types, meaning we get the standardized API (as done here). This can work for a `Shapefile.Polygon` as well as for a LibGEOS or GDAL pointer.

I was always thinking that the pure Julia packages such as Shapefile or GeoJSON could just agree on returning the same concrete type when reading files, but this is currently not the case, types much closer to the file type data format are used. Though I see GeoInterface has concrete types as well. I guess my question is how this relates to JuliaGeometry/GeometryTypes.jl#3.

**Comment by yeesian** [comment]
> Can you comment a bit on how you see the GeoInterface being used? How I see it now, we can make the types in the packages subtypes of the right GeoInterface abstract types, meaning we get the standardized API (as done here). This can work for a Shapefile.Polygon as well as for a LibGEOS or GDAL pointer. [...] I guess my question is how this relates to JuliaGeometry/GeometryTypes.jl#3.

Yeah, that's how I see it should be used for now too.

This is [the way it is currently done in Python](https://gist.github.com/sgillies/2217756), resulting in a workflow that looks something like http://www.perrygeo.com/processing-vector-features-in-python.html. But it's arguable whether this should be the way to go, since it can be very inefficient to request for the coordinates in the way a GeoJSON object expects them (from e.g. [Shapefile Polygons](https://github.com/JuliaGeo/Shapefile.jl/blob/57d672d57a1f76eedf45392f1190beca13618171/src/geo_interface.jl#L73-L111) which have a [different representation](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf)), especially if you intend to work with a package (e.g. RecipesBase.jl) which [expects the coordinates in yet-another-format](https://github.com/mkborregaard/Shapefile.jl/blob/9d00c042574dbeaa1045b692d16c49f58d44b35d/src/Plotsrecipe.jl#L3-L16).

It'll probably be better to have a more nuanced set of abstractions (like e.g. [DataStreams.jl](https://juliadata.github.io/DataStreams.jl/latest/) whose interface has evolved to be able to distinguish between column-based versus row-based databases). The most extensive effort that I've seen for geospatial geometries is based on the standards spelt out here http://www.opengeospatial.org/standards/sfa. This is the approach taken in [GDAL](http://www.gdal.org/) (Geospatial Data Abstraction Library; itself a port of [JTS](https://github.com/locationtech/jts)) which provides a C API for multi-language support.

But, given that the geo_interface in python has [received quite a lot of buy-in](http://geospatialpython.com/2013/05/new-geointerface-for-pyshp.html), and there's been quite a history of requests for map visualizations in Julia (e.g. on [discourse](https://discourse.julialang.org/t/package-for-map-visualizations/1875)), maybe it's worth adopting a [worse-is-better](http://dreamsongs.com/WorseIsBetter.html) approach, and start with what we have in GeoInterface.jl before adding methods in a piecemeal fashion to the interface.

> I was always thinking that the pure Julia packages such as Shapefile or GeoJSON could just agree on returning the same concrete type when reading files, but this is currently not the case, types much closer to the file type data format are used. Though I see GeoInterface has concrete types as well.

They could, but it's questionable to Shapefile users why they should experience the [parsing penalty of converting it into the GeoJSON format](https://github.com/JuliaGeo/Shapefile.jl/blob/57d672d57a1f76eedf45392f1190beca13618171/src/geo_interface.jl#L73-L111) given that it was not something they've requested for. I could also foresee the potential discussion over why the GeoJSON.jl package doesn't automatically convert its geometries into something supported by GeometryTypes.jl or Geodesy.jl. We've [had a similar discussion before](https://github.com/JuliaGeometry/meta/wiki/First-Meetup-Minutes), and it hasn't work out into something that package developers could agree upon (because of our differing requirements and use-cases).

The concrete types in GeoInterface are just there in an "incubation phase", and I can see them potentially (i) [moving into GeometryTypes](https://github.com/JuliaGeometry/GeometryTypes.jl/issues/3), (ii) being replaced by a sufficiently compelling offering, or (iii) being the first in a set of (yet-to-be-defined) canonical geospatial representations for other package developers. I see them our default/endorsement for package developers who don't care and don't want to have to figure out the choice between different GeoJSON/Shapefile/GDAL/future geometries.

One could ask: given that contributions to GDAL would have a much higher impact (given its multi-language support), is it really worth it to build a (probably similar/same) set of abstractions in Julia, given that (i) there really aren't many/any alternatives for geospatial geometries, and (ii) the amount of effort (to re-implement and maintain everything in Julia) can be immense.

**Comment by visr** [comment]
Thanks for taking the time to write that all down, it really helps following along.
I see R has a package with simple feature types represented natively in R (https://github.com/edzer/sfr). So perhaps that would be a good GeoInterface concrete type model (in the future)?

**Comment by yeesian** [comment]
> I see R has a package with simple feature types represented natively in R (https://github.com/edzer/sfr). So perhaps that would be a good GeoInterface concrete type model (in the future)?

Its license does not seem to be MIT/X-compatible, so I don't wish to dig into its source code. Also, it might often be that the bulk of the time is spent in other libraries, so it's important to minimize the amount of "serialization" (in converting the data from one type to another to match the requirements of various libraries that were "glued together").

We're supposed to promote generic programming, and not introduce another "middle-man" in the conversion between other geometry types, making our approach quite different from the `geo_interface` adopted by Python. Therefore, I'd prefer for any GeoInterface concrete type to be an implementation of the interface for packages (e.g. maybe https://github.com/yeesian/Turf.jl) to adopt GeoInterface without having to add any additional GeoJSON/LibGEOS/etc dependency just to have a concrete geometry object to run tests on.

**Pull request merged**
