### PR TITLE
fix duplicate holes

### LINKED ISSUE #65: `coordinates` on `Polygon` duplicates holes
I don't totally understand `coordinates(obj::Polygon)`, but it is possible to get duplicated holes in the output - the result of `coordinates` has more points than the original file. 

This seems to be caused by this break from the inner loop that does not break the outer loop:
https://github.com/JuliaGeo/Shapefile.jl/blob/1f52a7dfc789122abd482ac27a15f72fe550fcc9/src/geo_interface.jl#L86-L94

Is this a bug? The result is filling in holes in e.g. rasterization if you don't special-case it.

This seems to fix it:
```julia
    for hole in holes
        found = false
        for i = 1:nrings
            if inring(hole[1], coords[i][1])
                push!(coords[i], hole)
                found = true
                break
            end
        end
        if !found
            push!(coords, Vector{Vector{Float64}}[hole]) # hole is not inside any ring; make it a polygon
        end
    end
```

If that makes sense I'll PR

### PR DESCRIPTION
**Pull request by rafaqz**
This PR fixes the output of `coordinates` on all polygons, so that holes are not duplicated.

Also cleans up duplicate methods in geo_interface.jl

Closes #65

### CODE REVIEW

**Comment by rafaqz** [comment]
One downside to this is that holes don't show up in Plots.jl at all now - because the line that was showing was the duplicated hole that this PR removed. M

**Comment by visr** [comment]
Thanks for the PR!

> One downside to this is that holes don't show up in Plots.jl at all now - because the line that was showing was the duplicated hole that this PR removed.

I guess the fact that holes are not supported is known, judging by `# currently doesn't plot holes` comments in https://github.com/JuliaGeo/GeoInterface.jl/blob/master/src/plotrecipes.jl. Funny that this bug actually caused it to display holes however. If you know a way to get holes to display there that would be great, but that shouldn't hold back merging this.

**Review by visr — APPROVED** [review]

**Comment by rafaqz** [comment]
It just showed the outline of the hole, which is still a bug, but at least indicated that something was missing... We can keep that by appending the holes vector in the plot recipes?

This PR at least means that `Rasters.rasterize` will show the holes properly. That algorithm im using doesn't care about holes/not holes, but duplicate polygons make a double negative and the holes get filled.

Im not sure why or how the Plots.jl algorythms are different, I guess its all still vector graphics, and there is no way defined to link the hole and the area its cut from. But it would be good if this worked too...

**Comment by visr** [comment]
> Does it work for GeometryBasics.jl polygons with holes?

What do you mean? The GeometryBasics type supports holes (interiors): https://github.com/JuliaGeometry/GeometryBasics.jl/blob/ce718d9d3423c8b10c101d708e63a02967aaac40/src/basic_types.jl#L247-L256

But GeometryBasics does not implement the GeoInterface and also doesn't have Plots.jl recipes defined directly.

However if we take this example and update it for the test with holes: https://juliaplots.org/AlgebraOfGraphics.jl/dev/gallery/gallery/applications/geographic/#Geographic-data

```julia
using AlgebraOfGraphics, CairoMakie
using Shapefile

# exported from QGIS so it has an empty DBF
t = Shapefile.Table("test10.shp")

plt = geodata(t) * mapping(:geometry) * visual(Poly)
fg = draw(plt; axis=(aspect=1,))
```

Then we correctly see the holes:

plot_1

This works because AlgebraOfGraphics has functions to convert GeoInterface polygons to GeometryBasics.

However it'd probably be better if we:
1. Implement the GeoInterface in GeometryBasics
2. Directly return the GeometryBasics types in this package (#39)

**Comment by rafaqz** [comment]
I meant if holes in GeometryBasics work in Plots.jl, then that's the way to do this. If not then its a moot point. But it would be nice to have all of this just working some day. Good to see that holes at least work in Makie.jl.

I'm not sure about returning GeometryBasics.jl types here, that will e.g. break Rasters.jl polygon handling. Of course, integrating GeoInterface and GeometryBasics.jl is what we need. Doing it in AlgebraofGraphics is useful but isn't really the place for that interface.

**Comment by visr** [comment]
> I'm not sure about returning GeometryBasics.jl types here, that will e.g. break Rasters.jl polygon handling.

Why would it break if you are already using it through the GeoInterface? Provided the GeoInterface is added first to GeometryBasics.

**Comment by rafaqz** [comment]
> Provided the GeoInterface is added first to GeometryBasics.

Yep, but it isn't currently

**Comment by visr** [comment]
Yeah that's right, it would be a hard requirement before doing that, to avoid loss of functionality.

**Pull request merged**
