### PR TITLE
Write LineString as MultiLineString and Polygon as MultiPolygon

### PR DESCRIPTION
**Pull request by ErickChacon**
It fixes JuliaGeo/Shapefile.jl#89 and JuliaGeo/Shapefile.jl#88.

### CODE REVIEW

**Comment by rafaqz** [comment]
Some tests would be good

**Comment by ErickChacon** [comment]
It works with other packages for example with `GeoTables.jl` because it defines ncoord for the geometries associated with `GI.LineStringTrait` and `GI.PolygonTrait` :

```julia
using Meshes
import GeoTables as GT
import Shapefile ad SHP

points = Point2[(0,0),(0.5,2),(2.2,2.2)]
chain = Chain(points)
file = "chain.shp"
SHP.write(file, chain, force = true)

outer = Point2[(0,0),(0.5,2),(2.2,2.2),(0,0)]
poly = PolyArea(outer)
file = "poly.shp"
SHP.write(file, poly, force = true)
```

However it still is not working with native `SHP.LineString` and `SHP.SubPolygon` because the function `GI.ncoord` is not defined, so `GI.is3d` does not work as raised in issue #88. In order to have valid tests for this feature, we need PR #85 to be merged.

Do you still want me to add tests using `SHP.LineString` and `SHP.SubPolygon` knowing that it will fail until PR #85 is merged? Or maybe I could simply add also the `GI.ncoord` function for this geometries?

**Comment by rafaqz** [comment]
You can  totally move some code here from that PR, Im not sure how/when I will get that test passing as I cant reproduce the error.

**Comment by ErickChacon** [comment]
@rafaqz, I defined `GI.ncoord` for `GI.LineStringTrait` and `GI.PolygonTrait` and now it is working! It should also fix #88. It is really interesting how it was working for other packages thanks to the `GeoInterface.jl`!

**Comment by ErickChacon** [comment]
Just checking if I need to do something else for this PR to be accepted, so we call also merge JuliaEarth/GeoTables.jl#17.

**Pull request merged**
