### PR TITLE
Read polygons to GB.MultiPolygon

### PR DESCRIPTION
**Pull request by greimel**
see discussion in #39

### CODE REVIEW

**Comment by greimel** [comment]
I haven't figured out how to get the eltype for shapes array right.

**Comment by Sov-trotter** [comment]
So this is a bit tricky. Since `shapeType = read(io, Int32)` will return 5, i.e. `jltype = const Polygon` which is our multipolygonmeta. So isn't `shapes = Vector{jltype}(undef, 0)` right?

**Comment by greimel** [comment]
There is an issue with the tests.

The test shapefiles are not consistent with the technical description of shapefiles. Clockwise rings should be are exterior, counterclockwise rings should be interior.

 (see also here https://github.com/mbostock/shapefile/blob/ffe608804172efe53cc6761e51e379516db81ef2/shp/polygon.js#L8)

Here is a plot of the first test case:

clockwise

its exactly the other way round in the `test.shp`.

In `test10.shp` there are 4 polygons. 1, 2, 3 are without holes and run ccw (but should be cw!), 4 has two holes, they all run the right directions.

clockwise2

Can anyone tell me where the tests come from? IMO, the test cases are invalid and should be replaced.

**Comment by Sov-trotter** [comment]
So going by this, they are shapelib generated? https://github.com/JuliaGeo/Shapefile.jl/blob/master/test/shapelib_testcases/readme.txt

**Comment by visr** [comment]
Yeah makes me wonder how many of the shapefiles found in the wild match the spec 100%, and what deviations we should expect.

**Comment by Sov-trotter** [comment]
@greimel  can you try out the examples here? https://github.com/GeospatialPython/pyshp/tree/master/shapefiles/test
These seem to be maintained regularly.

**Comment by Sov-trotter** [comment]
So this is one of the polygons in the polygon.shp in the pyshp testcases. 
```
julia> tbl = Shapefile.Table("polygon.shp")

julia> mp = tbl.Geometry[1]
2-element GeometryBasics.MultiPolygon{

julia> mp = tbl.Geometry[1]
p = mp[1]

julia> p.exterior
5-element GeometryBasics.LineString{2,Float64,Point{2,Float64},Base.ReinterpretArray{GeometryBasics.Ngon{2,Float64,2,Point{2,Float64}},1,Tuple{Point{2,Float64},Point{2,Float64}},GeometryBasics.TupleView{Tuple{Point{2,Float64},Point{2,Float64}},2,1,Array{Point{2,Float64},1}}}}:
 Line([113.0, 24.0] => [112.0, 32.0])
 Line([112.0, 32.0] => [117.0, 36.0])
 Line([117.0, 36.0] => [122.0, 37.0])
 Line([122.0, 37.0] => [118.0, 20.0])
 Line([118.0, 20.0] => [113.0, 24.0])

julia> p.interiors[1]
4-element GeometryBasics.LineString{2,Float64,Point{2,Float64},Base.ReinterpretArray{GeometryBasics.Ngon{2,Float64,2,Point{2,Float64}},1,Tuple{Point{2,Float64},Point{2,Float64}},GeometryBasics.TupleView{Tuple{Point{2,Float64},Point{2,Float64}},2,1,Array{Point{2,Float64},1}}}}:
 Line([116.0, 29.0] => [116.0, 26.0])
 Line([116.0, 26.0] => [119.0, 29.0])
 Line([119.0, 29.0] => [119.0, 32.0])
 Line([119.0, 32.0] => [116.0, 29.0])
```
Screenshot from 2020-08-13 13-57-36

Here both the exterior and interior/holes run CW.

**Comment by greimel** [comment]
Inspecting the source, `pyshp` actually does what I propose

https://github.com/GeospatialPython/pyshp/blob/e0d436535ecf71fc22a7df61f38bd733e0f258aa/shapefile.py#L328

throw exception if there is not exterior ring:
https://github.com/GeospatialPython/pyshp/blob/e0d436535ecf71fc22a7df61f38bd733e0f258aa/shapefile.py#L425

**Comment by greimel** [comment]
> So this is one of the polygons in the polygon.shp in the pyshp testcases. [This is on `greimel:polygon`]
> 
> ```
> julia> tbl = Shapefile.Table("polygon.shp")
> 
> julia> mp = tbl.Geometry[1]
> 2-element GeometryBasics.MultiPolygon{
> 
> julia> mp = tbl.Geometry[1]
> p = mp[1]
> 
> julia> p.exterior
> 5-element GeometryBasics.LineString{2,Float64,Point{2,Float64},Base.ReinterpretArray{GeometryBasics.Ngon{2,Float64,2,Point{2,Float64}},1,Tuple{Point{2,Float64},Point{2,Float64}},GeometryBasics.TupleView{Tuple{Point{2,Float64},Point{2,Float64}},2,1,Array{Point{2,Float64},1}}}}:
>  Line([113.0, 24.0] => [112.0, 32.0])
>  Line([112.0, 32.0] => [117.0, 36.0])
>  Line([117.0, 36.0] => [122.0, 37.0])
>  Line([122.0, 37.0] => [118.0, 20.0])
>  Line([118.0, 20.0] => [113.0, 24.0])
> 
> julia> p.interiors[1]
> 4-element GeometryBasics.LineString{2,Float64,Point{2,Float64},Base.ReinterpretArray{GeometryBasics.Ngon{2,Float64,2,Point{2,Float64}},1,Tuple{Point{2,Float64},Point{2,Float64}},GeometryBasics.TupleView{Tuple{Point{2,Float64},Point{2,Float64}},2,1,Array{Point{2,Float64},1}}}}:
>  Line([116.0, 29.0] => [116.0, 26.0])
>  Line([116.0, 26.0] => [119.0, 29.0])
>  Line([119.0, 29.0] => [119.0, 32.0])
>  Line([119.0, 32.0] => [116.0, 29.0])
> ```
> 
> Screenshot from 2020-08-13 13-57-36
> 
> Here both the exterior and interior/holes run CW.

no, they run in the right directions. Otherwise they wouldn't be classified as exterior/interior correctly. (In the branch I am checking the directions.)

**Comment by SimonDanisch** [comment]
Nice!! :)

**Comment by SimonDanisch** [comment]
Ok, something goes pretty wrong here.
Black is parsed as the exterior, while red is the interior:

image

**Comment by greimel** [comment]
The code hasn’t been thoroughly tested yet, because of the issue above.

I’ll take the test files from the python library and test it tonight.

Sent from a mobile device. Please excuse brevity and errors.

Am 16.08.2020 um 19:18 schrieb Simon <notifications@github.com>:

﻿
Ok, something goes pretty wrong here.
Black is parsed as the exterior, while red is the interior:

**Comment by SimonDanisch** [comment]
We need to figure out a better task & thread model in the future... But not today :D

**Comment by SimonDanisch** [comment]
Oh my, accidentally merged this^^  welp, at least it just goes into my branch, which is fine I suppose

**Pull request merged**
