### PR TITLE
add Quick Start to README

### PR DESCRIPTION
**Pull request by cchderrick**
Added some very basic steps to read shapefile, I hope this helps.

### CODE REVIEW

**Comment by yeesian** [comment]
Thanks, it does!

Do you mind basing the example on a shapefile that readers can download and run?

**Comment by cchderrick** [comment]
does using test file works?
like adding this line `shapeFileName=joinpath(Pkg.dir(),"Shapefile","test","shapelib_testcases","test.shp")` ?

**Comment by yeesian** [comment]
Sure!

**Comment by yeesian** [comment]
Thanks for your contribution! :)

**Pull request merged**
