### PR TITLE
[WIP] .shp .shx writing

### PR DESCRIPTION
**Pull request by cchderrick**
Basically wanted to just mirror the read functions to write functions to start; we can add geo interface for writing shapefile geometries in another effort.

It is very messy computing `MBR`, `zrange` and `mrange`, any suggestions welcome.

TODO:
* [ ] - Add `.shx` writing
* [ ] - Add unit test

### CODE REVIEW

**Comment by visr** [comment]
This is nice, thanks for working on it!

Perhaps you can split out the calculations that compute the ranges into separate methods, and use dispatch instead of if else to pick the right method?

It may also be helpful to define some constants to avoid repeating long lists of types in your code, something like:
```julia
const Geometry = Union{Point,Polyline,Polygon,MultiPoint,PointZ,PolylineZ,PolygonZ,MultiPointZ,PointM,PolylineM,PolygonM,MultiPointM,MultiPatch}

write(::Geometry) = ...
```

**Comment by cchderrick** [comment]
hmm, apparently, I still had my VS Code on 1.0.3, didn't know it failed on 1.3.1

**Comment by visr** [comment]
Thanks for continuing this! So I see you now added write for

```
Base.write(io::IO, ::Type{Handle}, shapes::Array{Union{Missing,T}})
```

The `shapes` vector is part of the `Handle` type. Why did you choose for this signature as opposed to for instance `Base.write(io::IO, shp::Handle)`, perhaps accompanied by a constructor for `Handle` that takes a `shapes` vector and computes the ranges for the header?

Eventually for users I would imagine they mainly use one main read and write method to read and write `Shapefile.Table`:
https://github.com/JuliaGeo/Shapefile.jl/blob/8e4037332b79f799c88cc1ec64568c1899afd860/src/table.jl#L4-L6

Which would take care of everything. This of course requires all components to be in place, of which this (shp writing) is a major one. But that is probably best done in a separate PR, and also still needs DBF writing.

**Comment by cchderrick** [comment]
I think I didn't put too much thought on design; I had some time on a plane, and thought mindlessly mirroring the whole read process would be good for passing time.

With that said, I think I understand and agree with your assessment. I will try to refactor code to a constructor instead of a big gaint write function, and I think it help solving my problem with writing the same 100 bytes header for shx file.

**Comment by visr** [comment]
Productive flight :)

One other thing, I see you currently have different functions that are needed to build the header, such as `get_MBR` and `get_zrange`, that do a loop over all shapes. I'm not sure if these functions are ever needed individually. If not, it may be more efficient to get them all in one loop over the shapes.

**Pull request closed without merging**
