### PR TITLE
Add support for writing Feature Collection without properties

### PR DESCRIPTION
**Pull request by eliascarv**
Shapefile.jl breaks when writing a Feature Collection without properties.
MWE:
```
julia> import GeoJSON

julia> fc = GeoJSON.read("test.geojson")
FeatureCollection with 3 Features

julia> import Shapefile

julia> Shapefile.write("test.shp", fc)
ERROR: MethodError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer
Stacktrace:
  [1] reduce_empty(op::Base.MappingRF{Shapefile.var"#21#24", Base.BottomRF{…}}, ::Type{Tables.ColumnsRow{…}})
    @ Base ./reduce.jl:361
...
```
Contents of the `test.geojson` file:
```
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    0.0,
                    0.0
                ]
            },
            "properties": {}
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    1.0,
                    1.0
                ]
            },
            "properties": {}
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    2.0,
                    2.0
                ]
            },
            "properties": {}
        }
    ]
}
```

### CODE REVIEW

**Comment by rafaqz** [comment]
Thanks! 

That's a weird build error, you could try to isolate it by not running CI on Windows and/or 1.9

**Comment by eliascarv** [comment]
Sorry, I don't have permissions to run the CI.

**Comment by rafaqz** [comment]
Oh I just meant to comment it out in the workflow and push another commit.

Even with permissions github actions doesn't let us just trigger one on its own, it just runs everything so will probably kill the job from the same failure again.

**Comment by rafaqz** [comment]
Like here:
https://github.com/JuliaGeo/Shapefile.jl/blob/main/.github/workflows/CI.yml#L16

**Comment by eliascarv** [comment]
I honestly don't know what's going on with the CI, locally the tests pass.

**Comment by rafaqz** [comment]
Yep you're on 1.10 linux! Thats why I'm suggesting to comment out windows and 1.9 in the CI matrix and see what happens

https://github.com/JuliaGeo/Shapefile.jl/blob/main/.github/workflows/CI.yml#L16

**Comment by eliascarv** [comment]
Strange, now it works @rafaqz.

**Comment by rafaqz** [comment]
Not so strange :)

Not try with 1.9 but not windows, etc...

**Comment by eliascarv** [comment]
Commenting Windows only also works. Now I will comment only 1.9.

**Comment by eliascarv** [comment]
Commenting 1.9 only also works. The problem appears to be related to Julia 1.9 running on Windows.

**Comment by rafaqz** [comment]
Ah cool good that its only one. Not sure how to specify not testing that though! 

If you can work out how to not test 1.9 on windows that would be perfect, otherwise we can just turn off windows for now.

**Comment by eliascarv** [comment]
@rafaqz done. Ready for review.

**Review by rafaqz — APPROVED** [review]
LGTM

**Comment by eliascarv** [comment]
@rafaqz, can you release a patch with this PR?

**Pull request merged**
